### ISSUE TITLE
[FEATURE] Add support for the AllowZoneDrifting option

### ISSUE THREAD

**Issue by MarinBernard** [saltstack-formulas/firewalld-formula#44]
### Is your feature request related to a problem?

For [compatibility reasons](https://forums.centos.org/viewtopic.php?f=57&t=75335), RHEL/CentOS 7/8 firewalld packages come with zone drifting enabled by default, while best practices [are to keep it disabled](https://firewalld.org/2020/01/allowzonedrifting).

### Describe the solution you'd like

Disabling zone drifting requires adding `AllowZoneDrifting = no` to `/etc/firewalld/firewalld.conf`. Since this file is managed by the firewalld formula, it would be interesting to add support for this option to the formula.

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by myii** [comment]
@MarinBernard Thanks for the detailed feature request.  The links to sources is always appreciated.

Since the request is relatively simple, I've proposed #45 to resolve this issue.  It would be helpful if you could confirm that it works for you -- please add any feedback to that PR.

The proper resolution would involve implementing [TOFS](https://github.com/saltstack-formulas/template-formula/blob/master/docs/TOFS_pattern.rst) for this formula.  That would avoid needing to provide all of the possible configuration options in the template.
